### ISSUE TITLE
Failed to return after waiting for 10 seconds.

### ISSUE THREAD

**Issue by NuelNikhil** [adamhartford/SwiftR#26]
I have been trying SwiftR for a week. but when I ran the project I got nothing. In viewDidLoadMethod I have set this code

```
 SwiftR.connect("http://maisad-001-site1.btempurl.com/signalr/") { connection in
            let simpleHub = connection.createHubProxy("maisAdChatHub")
            print("HUBBBBB   \(simpleHub)")
                        SwiftR.startAll()
            print("HUBBBBB1   \(simpleHub)")
            // Event handler
            simpleHub.on("newMessage") { args in
//                let message = args!["0"] as! String
//                let detail = args!["1"] as! String
                print("Send Messageeeeeeeee")
                print("Response : \(args)")
                
                
                // Invoke server method
              //  simpleHub.invoke("sendSimple", arguments: ["Simple Test", "This is a simple message"])
                
                // Invoke server method and handle response
                simpleHub.invoke("sendmessage", arguments: ["Simple Test", "Room1" , "Usernamee" , "photo"]) { (result, error) in
                    if let e = error {
                        print("Error message: \(e)")
                    } else {
                        print("Success!")
                        if let r = result {
                            print("Result: \(r)")
                        }
                    }
                }

            }
        }
    }
```
I put a breakpoint at line number 7 where  **simpleHub.on("newMessage")** is called am getting a message in console and it is

_2016-02-02 15:04:33.131 CHATAPP[3089:374824] void SendDelegateMessage(NSInvocation *): delegate (webView:decidePolicyForNavigationAction:request:frame:decisionListener:) failed to return after waiting 10 seconds. main run loop mode: kCFRunLoopDefaultMode_

No Idea whats's going wrong... Need help!!!

**Comment by adamhartford** [comment]
You should only get that error message when debugging. The WebView stops executing JavaScript calls after 10 seconds. You will only hit that when you set a breakpoint somewhere in code that's part of a JavaScript callback. It's on my todo list to look at that, but it's been a very low priority since it's really been a non-issue so far.

As far as your code above, I see a few issues. I would suggest you try to get the demo app working with your server and go from there. The code should look more like this:

```swift
SwiftR.connect("http://maisad-001-site1.btempurl.com/signalr/") { connection in
    let simpleHub = connection.createHubProxy("maisAdChatHub")

    // Event handler
    simpleHub.on("newMessage") { args in
        print("Send Messageeeeeeeee")
        print("Response : \(args)")
    }
    
    connection.connected = {
        // Invoke server method and handle response
        simpleHub.invoke("sendmessage", arguments: ["Simple Test", "Room1" , "Usernamee" , "photo"]) { (result, error) in
            if let e = error {
                print("Error message: \(e)")
            } else {
                print("Success!")
                if let r = result {
                    print("Result: \(r)")
                }
            }
        }
    }
}
```

You don't need to call `SwiftR.startAll()`. You have everything happening in a callback handler for `newMessage`, so nothing will be invoked until the server sends `newMessage` to the client. Your `simpleHub` variable is also declared in the closure, so you can't access it anywhere else in your app. See the demo app for a different usage.

Lastly, it looks like you want to invoke a SignalR server method as soon as the client is connected, so I've tried to update your code accordingly. There's a callback for when the client has actually connected.

If you look at the code I've proposed above, you'll see that it:

1. Declares a hub.
2. Declares response callback for `newMessage`.
3. Invokes the server method `sendmessage` as soon as the client has established a SignalR connection.

This series of steps results in the newMessage callback handler being invoked as soon as possible after the view is loaded. I've run this code against my own test server to verify that it works.

From here, you'll just have to make sure your server methods are defined correctly, you're using the right names, etc.

**Comment by NuelNikhil** [comment]
I was looking for your @adamhartford   comments and I got what I was looking for... Let me try ... :+1:

**Comment by NuelNikhil** [comment]
@adamhartford  I tried running the SwiftR iOS Demo project. but I got this message in console

```
Starting...
Error: Optional({
    column = 4521;
    context =     {
        readyState = 0;
        status = 0;
        statusText = error;
    };
    errorMessage = "Error during negotiation request.";
    line = 8;
    source =     {
        readyState = 0;
        status = 0;
        statusText = error;
    };
    sourceURL = "file:///Users/user/Library/Developer/CoreSimulator/Devices/AB259C83-FD3F-4ABF-8F54-A8E07610B9D4/data/Containers/Data/Application/222A984A-58E4-4253-92F5-3F00955FEBE0/tmp/jquery.signalR-2.2.0.min";
})
Disconnected.
```

**Comment by adamhartford** [comment]
That means there's something wrong with your server. (Did you make sure the URL is correct?) What happens when you browse to http://maisad-001-site1.btempurl.com/signalr/hubs in a browser both on your desktop and on your phone?

**Comment by NuelNikhil** [comment]
I get the javascript code while browsing to `http://maisad-001-site1.btempurl.com/signalr/hubs `

**Comment by adamhartford** [comment]
OK, well that's a good sign. I think you should try to write a simple test page that uses the SignalR JavaScript client to test your server. If that works, there's no reason your iOS app shouldn't work as well. You could also try running [Charles Proxy ](http://www.charlesproxy.com) to inspect the traffic to your server. I've run the same code against my server and it works, so I'd probably need to see more of your iOS/.NET code to help you.

**Comment by NuelNikhil** [comment]
well .....I have tried the same code I got from your Github page in my server .

**Comment by adamhartford** [comment]
Have you tried Charles Proxy? Watch the traffic to the server, see what's happening? Also, what version of SignalR are you using?

**Comment by NuelNikhil** [comment]
This server is working fine for a developer who is creating a hybrid application. I don't know why it's not working for me.... and when I used Charles proxy it showed a 400 error... :-1:

**Comment by NuelNikhil** [comment]
when I run my project I get this in Charles 
![screen shot 2016-02-08 at 11 56 22 am](https://cloud.githubusercontent.com/assets/7767550/12879577/2e59662e-ce5b-11e5-8eae-712e1317345c.png)

and when I run the url `http://fridge.cynere.net/signalr/` I get this 
![screen shot 2016-02-08 at 11 55 34 am](https://cloud.githubusercontent.com/assets/7767550/12879585/403a6f78-ce5b-11e5-98f9-2a11def23b13.png)

**Comment by adamhartford** [comment]
A 400 is expected when browsing to /signalr. You should get a 200 with /signalr/hubs. Do you have CORS enabled on your server?

```csharp
// Server
app.UseCors (CorsOptions.AllowAll);
```

When you browse to /signalr/hubs, what version of the JavaScript library does it return?

**Comment by NuelNikhil** [comment]
I am currently using  SignalR version v2.2.0 and javascript library version returned is v2.1.1 and of-course  I have enabled CORS in my server...

**Comment by adamhartford** [comment]
Are you positive about CORS? I notice both URLs you've posted here are publicly available, so I tried both with WKWebView and get:

`Origin null is not allowed by Access-Control-Allow-Origin.`

That indicates CORS is not enabled. If I use UIWebView, the server returns an error (500).

**Comment by NuelNikhil** [comment]
I was working with swift and some others were doing backend. I checked our backend yesterday and found that no CORS were enabled. But I took the code and currently I am on it and  added the same code (both server code and client code) from SWIFTR example... but I didn't get my stuff woking. I have changed my URL too. currently it is  http://fridge.cynere.net/signalr/ .

**Comment by adamhartford** [comment]
Now I see: "You are using a version of the client that isn't compatible with the server. Client version 1.5, server version 1.4."

I don't know how you're using SignalR 2.2.0, but get 2.1.1 JavaScript. You should see 2.2.0 in the JavaScript as well.

If using NuGet, can you double check your packages? And maybe make sure you haven't deployed multiple versions of SignalR?

**Comment by NuelNikhil** [comment]
Sorry @adamhartford .... I am using signalr ver 2.1.1. it's my mistake I checked it in the nuget online packages rather than in the installed packages... I tried a lot with SWIFTR but it didn't even work. being new with iOS development I am not able get how your library works and what I need add to my code. I will try again. I will let you know my result's.... :+1:

**Comment by NuelNikhil** [comment]
when I run the charles proxy I got a 500 Internal Server Error...

**Comment by NuelNikhil** [comment]
Hi.. @adamhartford  I think a happy news...  Now I got a 200 status as response in by using charles. I took the Url from Charles and got this in browser `{"Url":"/signalr/signalr","ConnectionToken":"XPOVLO+P+t6r+m3r+Lr1CqchnP8KMi3eljkg6M7JZ0xwRk+C2Za73XMZC05uRQRN552XsBYGu40VfvvRmNUQdNQhPMjR8f0OSnu4RVF8nCVyTXYOvijqffDgA7SQgJyP","ConnectionId":"4537d793-960a-49ab-b684-b3b917acd7af","KeepAliveTimeout":20.0,"DisconnectTimeout":30.0,"TryWebSockets":false,"ProtocolVersion":"1.4","TransportConnectTimeout":5.0,"LongPollDelay":0.0}`

but in the demo project the code rans to the error section  as I have shown in the above question.

**Comment by adamhartford** [comment]
Looks like you're still using SignalR 2.1.1 instead of 2.2.0. Then, if you're still using the demo project, make sure you replace `simpleHub` with `Hub1` (which I can see in your JavaScript). Then make sure your `sendSimple` only sends one argument, not two like the demo (again I can see from your /signalr/hubs JS). That should work.

Also, I have a development version of SwiftR where you can now specify the server version you're using:

```swift
SwiftR.serverVersion = "2.1.1"
```

I might change this API depending on what versions I can support, but I can confirm that with my suggested changes above (and using 2.1.1), everything works.

Fo now, you'll need to make those changes, and be sure to run SignalR version 2.2.0.

**Comment by NuelNikhil** [comment]
one of our developer is working with a hybrid app and he uses signalr too. I used his server to test whether my code works , I have changed signalr version to 2.2.0 and did whatever I needed to but still no change .

**Comment by NuelNikhil** [comment]
we are getting a Newtonsoft.Json error and ocured after updating SIGNALR to 2.2.0. what all changes can I make ?

**Comment by NuelNikhil** [comment]
@adamhartford  Thank you for the replies you made all the time. Now everything is working fine... :+1:
