### ISSUE TITLE
On, Invoke does not return

### ISSUE THREAD

**Issue by jackyheart** [adamhartford/SwiftR#7]
I tried on Xcode7-beta, the 'on' function does not return ? Same thing with 'invoke'

**Comment by adamhartford** [comment]
I've only been using the Xcode 7 beta for trying Swift 2 and iOS 9. (SwiftR is not yet updated for either.) I'm guessing you're targeting iOS 8 in Xcode 7. If so, how? I'm able to install the iOS 8 simulator, but not select it as the base SDK for my targets. If you can help me with that, I can probably help you.

As an aside: do you have any issues in Xcode 6?

**Comment by jackyheart** [comment]
Hi Adam, yup, I'm targetting iOS8 in XCode 7. I'm able to run it on simulator, but I don't get any callbacks on 'on' & 'invoke'.

I've just tried on XCode 6, same thing, no callback.

Btw, how do you get the callback result on 'invoke' ? There's no callback block/closure on the 'invoke' method.

I've also tried the SignalR Obj-C version with XCode6, but the 'on' function doesn't return as well... It stops here: [SERVER_SENT_EVENTS]    SSE: GET <My URL>/signalr/signalr/connect.

**Comment by adamhartford** [comment]
You won't get a callback on `invoke`. That method invokes a SignlaR server-side method, which in turn invokes your `on` callback. See the SwifR demo application as an example.

```swift
// 1. Client: Inovkes SendComplex on SignalR server
complexHub.invoke("sendComplex", arguments: [message])
```

```csharp
// 2. Server: Invokes notifyComplex on connected clients
public void SendComplex(ComplexMessage message) 
{
    Clients.All.notifyComplex (message);
}
```

```swift
// 3. Client: handler method invoked as result of step 2
self?.complexHub.on("notifyComplex") { args in
   let m: AnyObject = args!["0"] as AnyObject!
   println(m)
}
```

Normally, you might have many clients listening for `notifyComplex`. Think of an example where you have many iOS clients connected to a SignalR server for sync. One of your devices tells SignlaR that data needs to be updated. SignalR tells your other iOS (or web, Android, whatever) clients.

In order to help, I'd need to see both your iOS client and SignalR server code. Do you have other clients already working properly with your SignalR server?

**Comment by jackyheart** [comment]
Hi Adam, it's working on 'on' now (XCode6 - Swift). Is there a connection id like the javascript or Android version ?

**Comment by adamhartford** [comment]
Cool. No, there is no way to access the connection ID right now, just because I haven't needed it in my own use. I can add it though if it'll help you.

**Comment by jackyheart** [comment]
Hi Adam, oh I see. Nvm, I can get it from the server instead. Thx !

**Comment by adamhartford** [comment]
You're welcome! FYI, I did make a change to provide the connection ID anyway in commit d561fdd8603240cac57eb8dd13279a014fb01991. The demo application shows how to get it.
